name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  pull-to-server:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install SSH Client
        run: sudo yum install -y openssh-clients

      - name: Add SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem
          eval "$(ssh-agent -s)"
          ssh-add key.pem

      - name: Git Pull to Server
        run: ssh -o StrictHostKeyChecking=no -p 6789 samudrawasesa@samudrawasesa.co.id 'cd /home/dev-wms.samudrawasesa.co.id/wms-samudra && git pull'
